/*
DROP DATABASE tpphp IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE filiere IF EXISTS;
DROP TABLE classe IF EXISTS;
*/

--  Creating the database 
CREATE DATABASE IF NOT EXISTS tpphp;
/* 
 Creating the databases for each 'filiere' & 'classe' & 'users'
 */

 -- to create tables inside the database tpPhp
use tpphp;
-- Defining the users table

CREATE TABLE IF NOT EXISTS users ( 
    id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    nom VARCHAR(40) NOT NULL,
    prenom VARCHAR(40) NOT NULL,
    email VARCHAR(50) NOT NULL,
    pass VARCHAR(256) NOT NULL,
    CONSTRAINT UN_Person UNIQUE (id, nom) 
);
    
    
-- Defining the filiere table


CREATE TABLE IF NOT EXISTS filiere (  
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    libelle VARCHAR(60) NOT NULL
);

-- Defining the classe table


CREATE TABLE IF NOT EXISTS classe ( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    id_f INT NOT NULL,
    FOREIGN KEY (id_f) REFERENCES filiere(id)
    ON DELETE CASCADE
);
/* 
=> adding a testing simples
the password is generated by using the function password_hach in PHP and the password hashed here is : "password"

for testing
*/
INSERT INTO users(nom, prenom, email, pass) VALUES("admin", "root", "testemail@gmail.com" , "$2y$10$3a6Io7ZbgUMPlNjdy0h6gOUeoY3n4O4c/pgyc6G4VzokhKQLB9hYC");
INSERT INTO filiere(code, libelle) VALUES ("2ITE", "Ingénierie Informatique et Technologies Emergentes");
INSERT INTO classe(code, id_f) VALUES("Programmation web et multiplate-formes", 1);



